name: Auto Deploy
on:
  push:
    branches: [main] # run on pushes to master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # setup the repository in the runner
      - name: Setup Node.js # setup Node.js in the runner
        with:
          node-version: '16'
      - name: Install and build
      - run: |
          npm # install dependencies
          npm run build --if-present
          npm run test
      # deploy site to netlify using secrets created on repository
      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
